services:
  db:
    image: postgres:15.5
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums -E utf8 --no-locale"
      TZ: "Asia/Seoul"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data: {}